[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "d2d-development"
version = "0.1.0"
description = "OpenHEXA DHIS2 to DHIS2 development utility library maintained by Bluesquare Data Services team."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openhexa-toolbox>=2.0.0",
    "openhexa.sdk>=1.0.0",
    "requests>=2.31.0",
    "pandas>=2.2.0",
    "polars>=1.0.0",
    "packaging>=23.0",
    "pyarrow>=10.0.0",
]

[project.optional-dependencies]
# These we only need to install when running the test, not when installing the package
dev = ["pytest", "pytest-cov", "ruff==0.15.22"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*"]

[tool.ruff]
line-length = 120

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 100

[tool.ruff.lint]
preview = true
select = [
    "F", # Pyflakes
    "E", # pycodestyle
    "I", # isort
    "D", # pydocstyle
    "UP", # pyupgrade
    "ANN", # flake8-annotations
    "B", # bugbear
    "A", # flake8-builtins
    "COM", # flake8-commas
    "FA", # flake8-future-annotations
    "PT", # flake8-pytest-style
    "Q", # flake8-quotes
    "RET", # flake8-return
    "SIM", # flake8-simplify
    "PTH", # flake8-use-pathlib
    "NPY", # NumPy rules
    "PD", # pandas rules
    "N", # pep8-naming
    "DOC", # pydoclint
    "PLC", # pylint convention
    "PLE", # pylint error
    "PLW", # pylint warning
    "RUF", # ruff specific rules
]

ignore = [
    "undocumented-public-module", # Missing docstring in public module
    "undocumented-public-package", # Missing docstring in public package
    "undocumented-magic-method", # Missing docstring in magic method
    "undocumented-public-nested-class", # Missing docstring in public nested class
    "undocumented-public-init", # Missing docstring in __init__
    "non-imperative-mood", # First line should be in imperative mood
    "missing-blank-line-after-last-section", # Missing blank line after last section
    "incorrect-blank-line-before-class", # 1 blank line required before class docstring
    "multi-line-summary-second-line", # Multi-line docstring summary should start at the second line (conflicts with D212)
    "if-else-block-instead-of-if-exp", # Use ternary operators
    "collapsible-if", # Use a single if statement instead of nested if statements
    "if-with-same-arms", # Combine `if` branches
    "docstring-missing-exception", # Raised exception {id} missing from docstring	
    "docstring-extraneous-exception", # Raised exception is not explicitly raised: {id}	
    "unsorted-dunder-all", # `__all__` is not sorted
    "collection-literal-concatenation", # Consider expression instead of concatenation
    "float-equality-comparison", # Unreliable floating point equality comparison
    "noqa-comments", # `noqa` comment used instead of `ruff: ignore` (opinionated preview rule, noqa is fine)
    "too-many-public-methods", # Too many public methods ({methods} > {max_methods})
    "too-many-return-statements", # Too many return statements ({returns} > {max_returns})
    "too-many-branches", # Too many branches ({branches} > {max_branches})
    "too-many-arguments", # Too many arguments ({arguments} > {max_arguments})
    "too-many-locals", # Too many local variables ({variables} > {max_variables})
    "too-many-statements", # Too many statements ({statements} > {max_statements})
    "too-many-boolean-expressions", # Too many Boolean expressions ({expressions} > {max_expressions})
    "too-many-nested-blocks", # Too many nested blocks ({blocks} > {max_blocks}),
    "missing-trailing-comma", # Missing trailing comma
]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true
mypy-init-return = true
suppress-dummy-args = true
suppress-none-returning = true